### ISSUE TITLE
ERROR: Failure: AttributeError ('NoneType' object has no attribute 'endswith')

### ISSUE THREAD

**Issue by kartikdanidhariya** [tubaman/mosaico-server-tests#1]
hi i want to use your library in my project 
for that i create one virtualenv and install all dependency in that after set environment variable in virtualenv for that i added all three variable 
in bin/activate file 

export MOSAICO_URL=http://127.0.0.1:9006
export MOSAICO_DIR=None
export TEST_PHOTO=None

after i run nosetests

but it return error like
## ERROR: Failure: AttributeError ('NoneType' object has no attribute 'endswith')

Traceback (most recent call last):
  File "/home/vrs/mosaico/mosaico/local/lib/python2.7/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/home/vrs/mosaico/mosaico/local/lib/python2.7/site-packages/nose/loader.py", line 570, in _makeTest
    return self.loadTestsFromTestCase(obj)
  File "/home/vrs/mosaico/mosaico/local/lib/python2.7/site-packages/nose/loader.py", line 494, in loadTestsFromTestCase
    return super(TestLoader, self).loadTestsFromTestCase(testCaseClass)
  File "/usr/lib/python2.7/unittest/loader.py", line 56, in loadTestsFromTestCase
    loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
  File "/home/vrs/mosaico/mosaico/mosaico-server-tests-master/tests.py", line 18, in __init__
    self.upload_dir = os.path.join(mosaico_dir, 'uploads')
  File "/home/vrs/mosaico/mosaico/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

how can i solve this error

**Comment by tubaman** [comment]
Sorry for the late reply.  I suppose the README is a little confusing.
You must explictly set[1] MOSAICO_DIR.  It can't be left as 'None'.  So,
you should do something like:

export MOSAICO_URL=http://127.0.0.1:9006
export MOSAICO_DIR=/home/myuser/mosaico
export TEST_PHOTO=/home/myuser/Photos/mytestphoto.jpg
- Ryan

[1] https://github.com/tubaman/mosaico-server-tests/blob/master/README.md

**Comment by tubaman** [comment]
I've updated the README to hopefully make it more clear:
https://github.com/tubaman/mosaico-server-tests/blob/master/README.md
- Ryan
